In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data, digits.target, test_size=0.3)

# LogisticRegression

In [16]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9555555555555556

# SVM

In [17]:
svm = SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.4148148148148148

# Random Forest

In [42]:
rf = RandomForestClassifier(n_estimators=50)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9814814814814815

# KFold Cross Validation

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [28]:
for train_index, test_index in kf.split([1,2,3,4,12,1,5,2,6,3,7,44,8,9,35,86,4,35,8,52,2,3,78,654,45,643,765,7]):
    print(train_index, test_index)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27] [0 1 2 3 4 5]
[ 0  1  2  3  4  5 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27] [ 6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 18 19 20 21 22 23 24 25 26 27] [12 13 14 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 23 24 25 26 27] [18 19 20 21 22]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22] [23 24 25 26 27]


In [29]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [31]:
get_score(lr, X_train, X_test, y_train, y_test)

0.9555555555555556

In [32]:
get_score(svm, X_train, X_test, y_train, y_test)

0.4148148148148148

In [33]:
get_score(rf, X_train, X_test, y_train, y_test)

0.9796296296296296

In [50]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

score_logistic = []
score_svm = []
score_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))

In [51]:
score_logistic

[0.9222222222222223,
 0.8833333333333333,
 0.9526462395543176,
 0.958217270194986,
 0.8941504178272981]

In [52]:
score_svm

[0.4111111111111111,
 0.45,
 0.45403899721448465,
 0.44846796657381616,
 0.479108635097493]

In [53]:
score_rf

[0.9333333333333333,
 0.9055555555555556,
 0.958217270194986,
 0.9749303621169917,
 0.924791086350975]

In [54]:
from sklearn.model_selection import cross_val_score

In [55]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])